template_name_prefix     = "instance"
template_image_id        = "ami-05339d597592d45cf"
template_instance_type   = "t2.micro"
asg_name                 = "asg_ecs"
asg_iam_instance_profile = "arn:aws:iam::171214049742:instance-profile/ecsInstanceRole"
asg_desired_capacity     = 1
asg_max_size             = 2
asg_min_size             = 1
asg_vpc_zone_identifier  = ["subnet-077327517914c963d", "subnet-0bf28506e12273c09"]
lauch_version            = "$Latest"
ecs_cluster_name         = "ecs-cluster"
ecs_capacity_name        = "capacityProvider"
service_name = "ecs_service"
task_family = "ecs-task-1"
task_cpu = 256
task_memory = 250
task_compatibilities = ["EC2"]
task_network = "bridge"